services:
  - type: web
    name: finmate-api
    runtime: node
    region: singapore
    plan: free
    buildCommand: pnpm install && pnpm turbo run build --filter=backend-api
    startCommand: node apps/backend-api/dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
