// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: amc.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAmcBySlug = `-- name: GetAmcBySlug :one
SELECT id, slug, name, sebi_reg_no, website, logo_url,
       total_aum_cr, scheme_count, scraper_status, last_scraped_at,
       created_at, updated_at
FROM fundlens.amc
WHERE slug = $1
`

func (q *Queries) GetAmcBySlug(ctx context.Context, slug string) (FundlensAmc, error) {
	row := q.db.QueryRow(ctx, getAmcBySlug, slug)
	var i FundlensAmc
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.SebiRegNo,
		&i.Website,
		&i.LogoUrl,
		&i.TotalAumCr,
		&i.SchemeCount,
		&i.ScraperStatus,
		&i.LastScrapedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAmcs = `-- name: ListAmcs :many
SELECT id, slug, name, logo_url, total_aum_cr, scheme_count,
       scraper_status, last_scraped_at
FROM fundlens.amc
WHERE scraper_status IN ('active', 'broken')
ORDER BY total_aum_cr DESC NULLS LAST
`

type ListAmcsRow struct {
	ID            int64              `json:"id"`
	Slug          string             `json:"slug"`
	Name          string             `json:"name"`
	LogoUrl       *string            `json:"logo_url"`
	TotalAumCr    pgtype.Numeric     `json:"total_aum_cr"`
	SchemeCount   *int32             `json:"scheme_count"`
	ScraperStatus string             `json:"scraper_status"`
	LastScrapedAt pgtype.Timestamptz `json:"last_scraped_at"`
}

func (q *Queries) ListAmcs(ctx context.Context) ([]ListAmcsRow, error) {
	rows, err := q.db.Query(ctx, listAmcs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAmcsRow
	for rows.Next() {
		var i ListAmcsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.LogoUrl,
			&i.TotalAumCr,
			&i.SchemeCount,
			&i.ScraperStatus,
			&i.LastScrapedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
