// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: diff.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listDiffsByScheme = `-- name: ListDiffsByScheme :many
SELECT isin, prev_qty, curr_qty, qty_delta,
       prev_value_cr, curr_value_cr, action
FROM fundlens.holding_diff
WHERE scheme_id = $1
  AND curr_snapshot_id = $2
ORDER BY ABS(COALESCE(curr_value_cr, 0) - COALESCE(prev_value_cr, 0)) DESC NULLS LAST
`

type ListDiffsBySchemeParams struct {
	SchemeID       int64  `json:"scheme_id"`
	CurrSnapshotID *int64 `json:"curr_snapshot_id"`
}

type ListDiffsBySchemeRow struct {
	Isin        string         `json:"isin"`
	PrevQty     pgtype.Numeric `json:"prev_qty"`
	CurrQty     pgtype.Numeric `json:"curr_qty"`
	QtyDelta    pgtype.Numeric `json:"qty_delta"`
	PrevValueCr pgtype.Numeric `json:"prev_value_cr"`
	CurrValueCr pgtype.Numeric `json:"curr_value_cr"`
	Action      string         `json:"action"`
}

func (q *Queries) ListDiffsByScheme(ctx context.Context, arg ListDiffsBySchemeParams) ([]ListDiffsBySchemeRow, error) {
	rows, err := q.db.Query(ctx, listDiffsByScheme, arg.SchemeID, arg.CurrSnapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDiffsBySchemeRow
	for rows.Next() {
		var i ListDiffsBySchemeRow
		if err := rows.Scan(
			&i.Isin,
			&i.PrevQty,
			&i.CurrQty,
			&i.QtyDelta,
			&i.PrevValueCr,
			&i.CurrValueCr,
			&i.Action,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
