// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: holding.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listHoldingsBySnapshot = `-- name: ListHoldingsBySnapshot :many
SELECT id, isin, ticker_nse, company_name, sector,
       quantity, market_value_cr, pct_of_nav
FROM fundlens.holding
WHERE snapshot_id = $1
ORDER BY market_value_cr DESC NULLS LAST
`

type ListHoldingsBySnapshotRow struct {
	ID            int64          `json:"id"`
	Isin          *string        `json:"isin"`
	TickerNse     *string        `json:"ticker_nse"`
	CompanyName   string         `json:"company_name"`
	Sector        *string        `json:"sector"`
	Quantity      pgtype.Numeric `json:"quantity"`
	MarketValueCr pgtype.Numeric `json:"market_value_cr"`
	PctOfNav      pgtype.Numeric `json:"pct_of_nav"`
}

func (q *Queries) ListHoldingsBySnapshot(ctx context.Context, snapshotID int64) ([]ListHoldingsBySnapshotRow, error) {
	rows, err := q.db.Query(ctx, listHoldingsBySnapshot, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHoldingsBySnapshotRow
	for rows.Next() {
		var i ListHoldingsBySnapshotRow
		if err := rows.Scan(
			&i.ID,
			&i.Isin,
			&i.TickerNse,
			&i.CompanyName,
			&i.Sector,
			&i.Quantity,
			&i.MarketValueCr,
			&i.PctOfNav,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
