// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type FundlensAmc struct {
	ID            int64              `json:"id"`
	Slug          string             `json:"slug"`
	Name          string             `json:"name"`
	SebiRegNo     *string            `json:"sebi_reg_no"`
	Website       *string            `json:"website"`
	LogoUrl       *string            `json:"logo_url"`
	TotalAumCr    pgtype.Numeric     `json:"total_aum_cr"`
	SchemeCount   *int32             `json:"scheme_count"`
	ScraperStatus string             `json:"scraper_status"`
	LastScrapedAt pgtype.Timestamptz `json:"last_scraped_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type FundlensFundManager struct {
	ID        int64              `json:"id"`
	AmcID     int64              `json:"amc_id"`
	Name      string             `json:"name"`
	SinceDate pgtype.Date        `json:"since_date"`
	Bio       *string            `json:"bio"`
	PhotoUrl  *string            `json:"photo_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type FundlensHolding struct {
	ID            int64          `json:"id"`
	SnapshotID    int64          `json:"snapshot_id"`
	Isin          *string        `json:"isin"`
	TickerNse     *string        `json:"ticker_nse"`
	TickerBse     *string        `json:"ticker_bse"`
	CompanyName   string         `json:"company_name"`
	Sector        *string        `json:"sector"`
	Quantity      pgtype.Numeric `json:"quantity"`
	MarketValueCr pgtype.Numeric `json:"market_value_cr"`
	PctOfNav      pgtype.Numeric `json:"pct_of_nav"`
}

type FundlensHoldingDiff struct {
	ID             int64              `json:"id"`
	SchemeID       int64              `json:"scheme_id"`
	Isin           string             `json:"isin"`
	PrevSnapshotID *int64             `json:"prev_snapshot_id"`
	CurrSnapshotID *int64             `json:"curr_snapshot_id"`
	PrevQty        pgtype.Numeric     `json:"prev_qty"`
	CurrQty        pgtype.Numeric     `json:"curr_qty"`
	QtyDelta       pgtype.Numeric     `json:"qty_delta"`
	PrevValueCr    pgtype.Numeric     `json:"prev_value_cr"`
	CurrValueCr    pgtype.Numeric     `json:"curr_value_cr"`
	Action         string             `json:"action"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type FundlensHoldingsSnapshot struct {
	ID              int64              `json:"id"`
	SchemeID        int64              `json:"scheme_id"`
	DisclosureDate  pgtype.Date        `json:"disclosure_date"`
	AumAtDisclosure pgtype.Numeric     `json:"aum_at_disclosure"`
	RawFileUrl      string             `json:"raw_file_url"`
	RawFileSha256   string             `json:"raw_file_sha256"`
	ParsedAt        pgtype.Timestamptz `json:"parsed_at"`
	ParserVersion   string             `json:"parser_version"`
}

type FundlensIsinMaster struct {
	Isin        string             `json:"isin"`
	TickerNse   *string            `json:"ticker_nse"`
	TickerBse   *string            `json:"ticker_bse"`
	CompanyName string             `json:"company_name"`
	Sector      *string            `json:"sector"`
	Industry    *string            `json:"industry"`
	RefreshedAt pgtype.Timestamptz `json:"refreshed_at"`
}

type FundlensNav struct {
	ID       int64          `json:"id"`
	SchemeID int64          `json:"scheme_id"`
	Date     pgtype.Date    `json:"date"`
	Nav      pgtype.Numeric `json:"nav"`
}

type FundlensScheme struct {
	ID           int64              `json:"id"`
	AmcID        int64              `json:"amc_id"`
	ManagerID    *int64             `json:"manager_id"`
	AmfiCode     *string            `json:"amfi_code"`
	IsinGrowth   *string            `json:"isin_growth"`
	IsinIdcw     *string            `json:"isin_idcw"`
	Name         string             `json:"name"`
	Slug         string             `json:"slug"`
	Category     *string            `json:"category"`
	SubCategory  *string            `json:"sub_category"`
	Benchmark    *string            `json:"benchmark"`
	AumCr        pgtype.Numeric     `json:"aum_cr"`
	ExpenseRatio pgtype.Numeric     `json:"expense_ratio"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
