// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: nav.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listNavByScheme = `-- name: ListNavByScheme :many
SELECT date, nav
FROM fundlens.nav
WHERE scheme_id = $1
  AND date >= $2
  AND date <= $3
ORDER BY date ASC
`

type ListNavBySchemeParams struct {
	SchemeID int64       `json:"scheme_id"`
	Date     pgtype.Date `json:"date"`
	Date_2   pgtype.Date `json:"date_2"`
}

type ListNavBySchemeRow struct {
	Date pgtype.Date    `json:"date"`
	Nav  pgtype.Numeric `json:"nav"`
}

func (q *Queries) ListNavByScheme(ctx context.Context, arg ListNavBySchemeParams) ([]ListNavBySchemeRow, error) {
	rows, err := q.db.Query(ctx, listNavByScheme, arg.SchemeID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNavBySchemeRow
	for rows.Next() {
		var i ListNavBySchemeRow
		if err := rows.Scan(&i.Date, &i.Nav); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
