// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	GetAmcBySlug(ctx context.Context, slug string) (FundlensAmc, error)
	GetLatestSnapshotForScheme(ctx context.Context, schemeID int64) (GetLatestSnapshotForSchemeRow, error)
	GetSchemeBySlug(ctx context.Context, slug string) (GetSchemeBySlugRow, error)
	ListAmcs(ctx context.Context) ([]ListAmcsRow, error)
	ListDiffsByScheme(ctx context.Context, arg ListDiffsBySchemeParams) ([]ListDiffsBySchemeRow, error)
	ListHoldersOfIsin(ctx context.Context, arg ListHoldersOfIsinParams) ([]ListHoldersOfIsinRow, error)
	ListHoldingsBySnapshot(ctx context.Context, snapshotID int64) ([]ListHoldingsBySnapshotRow, error)
	ListNavByScheme(ctx context.Context, arg ListNavBySchemeParams) ([]ListNavBySchemeRow, error)
	ListSchemesByAmc(ctx context.Context, arg ListSchemesByAmcParams) ([]ListSchemesByAmcRow, error)
}

var _ Querier = (*Queries)(nil)
