// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: scheme.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestSnapshotForScheme = `-- name: GetLatestSnapshotForScheme :one
SELECT id, disclosure_date
FROM fundlens.holdings_snapshot
WHERE scheme_id = $1
ORDER BY disclosure_date DESC LIMIT 1
`

type GetLatestSnapshotForSchemeRow struct {
	ID             int64       `json:"id"`
	DisclosureDate pgtype.Date `json:"disclosure_date"`
}

func (q *Queries) GetLatestSnapshotForScheme(ctx context.Context, schemeID int64) (GetLatestSnapshotForSchemeRow, error) {
	row := q.db.QueryRow(ctx, getLatestSnapshotForScheme, schemeID)
	var i GetLatestSnapshotForSchemeRow
	err := row.Scan(&i.ID, &i.DisclosureDate)
	return i, err
}

const getSchemeBySlug = `-- name: GetSchemeBySlug :one
SELECT s.id, s.slug, s.name, s.category, s.sub_category,
       s.aum_cr, s.expense_ratio, s.amfi_code, s.isin_growth, s.isin_idcw,
       a.name AS amc_name, a.slug AS amc_slug
FROM fundlens.scheme s
JOIN fundlens.amc a ON a.id = s.amc_id
WHERE s.slug = $1
`

type GetSchemeBySlugRow struct {
	ID           int64          `json:"id"`
	Slug         string         `json:"slug"`
	Name         string         `json:"name"`
	Category     *string        `json:"category"`
	SubCategory  *string        `json:"sub_category"`
	AumCr        pgtype.Numeric `json:"aum_cr"`
	ExpenseRatio pgtype.Numeric `json:"expense_ratio"`
	AmfiCode     *string        `json:"amfi_code"`
	IsinGrowth   *string        `json:"isin_growth"`
	IsinIdcw     *string        `json:"isin_idcw"`
	AmcName      string         `json:"amc_name"`
	AmcSlug      string         `json:"amc_slug"`
}

func (q *Queries) GetSchemeBySlug(ctx context.Context, slug string) (GetSchemeBySlugRow, error) {
	row := q.db.QueryRow(ctx, getSchemeBySlug, slug)
	var i GetSchemeBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Category,
		&i.SubCategory,
		&i.AumCr,
		&i.ExpenseRatio,
		&i.AmfiCode,
		&i.IsinGrowth,
		&i.IsinIdcw,
		&i.AmcName,
		&i.AmcSlug,
	)
	return i, err
}

const listSchemesByAmc = `-- name: ListSchemesByAmc :many
SELECT id, slug, name, category, sub_category, aum_cr, expense_ratio,
       amfi_code, isin_growth, isin_idcw
FROM fundlens.scheme
WHERE amc_id = $1
ORDER BY aum_cr DESC NULLS LAST
LIMIT $2 OFFSET $3
`

type ListSchemesByAmcParams struct {
	AmcID  int64 `json:"amc_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListSchemesByAmcRow struct {
	ID           int64          `json:"id"`
	Slug         string         `json:"slug"`
	Name         string         `json:"name"`
	Category     *string        `json:"category"`
	SubCategory  *string        `json:"sub_category"`
	AumCr        pgtype.Numeric `json:"aum_cr"`
	ExpenseRatio pgtype.Numeric `json:"expense_ratio"`
	AmfiCode     *string        `json:"amfi_code"`
	IsinGrowth   *string        `json:"isin_growth"`
	IsinIdcw     *string        `json:"isin_idcw"`
}

func (q *Queries) ListSchemesByAmc(ctx context.Context, arg ListSchemesByAmcParams) ([]ListSchemesByAmcRow, error) {
	rows, err := q.db.Query(ctx, listSchemesByAmc, arg.AmcID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSchemesByAmcRow
	for rows.Next() {
		var i ListSchemesByAmcRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Category,
			&i.SubCategory,
			&i.AumCr,
			&i.ExpenseRatio,
			&i.AmfiCode,
			&i.IsinGrowth,
			&i.IsinIdcw,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
