// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: stock.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listHoldersOfIsin = `-- name: ListHoldersOfIsin :many
WITH latest_per_scheme AS (
  SELECT DISTINCT ON (scheme_id) id AS snapshot_id, scheme_id, disclosure_date
  FROM fundlens.holdings_snapshot
  ORDER BY scheme_id, disclosure_date DESC
)
SELECT s.slug, s.name AS scheme_name, a.name AS amc_name,
       h.quantity, h.market_value_cr, h.pct_of_nav,
       lps.disclosure_date
FROM latest_per_scheme lps
JOIN fundlens.holding h ON h.snapshot_id = lps.snapshot_id
JOIN fundlens.scheme s ON s.id = lps.scheme_id
JOIN fundlens.amc a ON a.id = s.amc_id
WHERE h.isin = $1
ORDER BY h.market_value_cr DESC NULLS LAST
LIMIT $2 OFFSET $3
`

type ListHoldersOfIsinParams struct {
	Isin   *string `json:"isin"`
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
}

type ListHoldersOfIsinRow struct {
	Slug           string         `json:"slug"`
	SchemeName     string         `json:"scheme_name"`
	AmcName        string         `json:"amc_name"`
	Quantity       pgtype.Numeric `json:"quantity"`
	MarketValueCr  pgtype.Numeric `json:"market_value_cr"`
	PctOfNav       pgtype.Numeric `json:"pct_of_nav"`
	DisclosureDate pgtype.Date    `json:"disclosure_date"`
}

func (q *Queries) ListHoldersOfIsin(ctx context.Context, arg ListHoldersOfIsinParams) ([]ListHoldersOfIsinRow, error) {
	rows, err := q.db.Query(ctx, listHoldersOfIsin, arg.Isin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHoldersOfIsinRow
	for rows.Next() {
		var i ListHoldersOfIsinRow
		if err := rows.Scan(
			&i.Slug,
			&i.SchemeName,
			&i.AmcName,
			&i.Quantity,
			&i.MarketValueCr,
			&i.PctOfNav,
			&i.DisclosureDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
